### ISSUE TITLE
Which head to use when test?

### ISSUE THREAD

**Issue by ppaanngggg** [musyoku/reinforcement-learning#1]
Thank you for your nice code of bootstrapped DQN.

However I have a question about the algorithm which I can't find from paper or code. :(

I wonder which head to use when test? Any one is OK? or use average?

**Comment by musyoku** [comment]
Actually, this code is still under development because I don't get any result described in the paper.
And I have no idea which head to use when test.

**Comment by ppaanngggg** [comment]
I guess that maybe there is another head not masked

**Comment by ppaanngggg** [comment]
According to this video https://www.youtube.com/watch?v=0jvEcC5JvGY&feature=youtu.be,

I think the final action is voted when test

**Comment by musyoku** [comment]
It appears so.

By the way, I'm not sure what "bootstrap mask" in Algorithm1 is for.

**Comment by ppaanngggg** [comment]
Implenement of mask in your code is direct. But yours is much different from https://github.com/iassael/torch-bootstrapped-dqn

**Comment by ppaanngggg** [comment]
The head in your code is only one layer Linear. Will a more powerful model be better?
